name: Update Sub Files Every 10 Minutes

on:
  schedule:
    - cron: '*/20 * * * *'  # 
  workflow_dispatch:        # Ø§

jobs:
  update-subs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v3
      with:
        ref: main  # 

    - name: Copy script from automation branch
      run: |
        git fetch origin automation
        git checkout origin/automation -- change_remark_all_types.py

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run remark updater script
      run: python change_remark_all_types.py "á›–á›ˆá›Ÿá›á›Ÿáš¾á›á›Ÿá›Š"

    - name: Commit and push changes to main
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add Sub*.txt
        git commit -m "FreshğŸ”¥â¤ï¸â€ğŸ”¥ğŸ†" || echo "No changes"
        git push origin main
